# Site settings
title: Aziz Abbas
email: teleaziz@gmail.com
description: "A son, friend, hacker, entreprenuer,coffee trailblazer and food enthusiast. "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/teleaziz
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: http://github.com/teleaziz

# Postal address (add as many lines as necessary)
address:
  - line: Mountain View , CA

# Build settings
markdown: kramdown
permalink: pretty
